#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VitruvianApp2016.Droid.Resource", IsApplication=true)]

namespace VitruvianApp2016.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
<<<<<<< HEAD
=======
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::VitruvianApp2016.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::VitruvianApp2016.Droid.Resource.String.Hello;
>>>>>>> 2cbb42c73b2a977ea0d0e3196afdd90918c0acf5
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
<<<<<<< HEAD
=======
			// aapt resource value: 0x7f020001
			public const int Placeholder_image_placeholder = 2130837505;
			
>>>>>>> 2cbb42c73b2a977ea0d0e3196afdd90918c0acf5
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
<<<<<<< HEAD
=======
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
>>>>>>> 2cbb42c73b2a977ea0d0e3196afdd90918c0acf5
	}
}
#pragma warning restore 1591
